ClassCentral\CredentialBundle\Entity\CredentialReview:
    type: entity
    table: credentials_reviews
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        rating:
            type: float
            nullable: false
        title:
            type: text
            nullable: true
        text:
            type: text
            nullable: true
        status:
            type: integer
            unsigned: false
            nullable: false
        dateCompleted:
            type: date
            nullable: true
            column: date_completed
        link:
            type: text
            nullable: true
        topicCoverage:
            type: float
            nullable: true
            column: topic_coverage
        jobReadiness:
            type: float
            nullable: true
            column: job_readiness
        communitySupport:
            type: float
            nullable: true
            column: community_support
        effort:
            type: integer
            unsigned: false
            nullable: true
        duration:
            type: integer
            unsigned: false
            nullable: true
        reviewerName:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: reviewer_name
        reviewerEmail:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: reviewer_email
        reviewerJobTitle:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: reviewer_job_title
        reviewerHighestDegree:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: reviewer_highest_degree
        reviewerFieldOfStudy:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: reviewer_field_of_study
        created:
            type: datetime
            nullable: true
        modified:
            type: datetime
            nullable: false
    manyToOne:
        credential:
            targetEntity: Credential
            cascade: {  }
            mappedBy: null
            inversedBy: reviews
            joinColumns:
                credential_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: ClassCentral\SiteBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: credentialReviews
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
