ClassCentral\CredentialBundle\Entity\CredentialCourses:
    type: entity
    table: credentials_courses
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        order:
            type: integer
            unsigned: false
            nullable: false
    manyToOne:
        credential:
            targetEntity: Credential
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                credential_id:
                    referencedColumnName: id
            orphanRemoval: false
        course:
            targetEntity: ClassCentral\SiteBundle\Entity\Course
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                course_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
