ClassCentral\CredentialBundle\Entity\Credential:
    type: entity
    table: credentials
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: text
            nullable: false
        oneLiner:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: one_liner
        price:
            type: integer
            unsigned: false
            nullable: false
        pricePeriod:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: price_period
        durationMin:
            type: integer
            unsigned: false
            nullable: true
            column: duration_min
        durationMax:
            type: integer
            unsigned: false
            nullable: true
            column: duration_max
        workloadMin:
            type: integer
            unsigned: false
            nullable: true
            column: workload_min
        workloadMax:
            type: integer
            unsigned: false
            nullable: true
            column: workload_max
        workloadType:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: workload_type
        url:
            type: text
            nullable: false
        description:
            type: text
            nullable: true
        created:
            type: datetime
            nullable: true
        modified:
            type: datetime
            nullable: false
    oneToMany:
        reviews:
            targetEntity: CredentialReview
            mappedBy: credential
    manyToOne:
        initiative:
            targetEntity: ClassCentral\SiteBundle\Entity\Initiative
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                initiative_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        institutions:
            targetEntity: ClassCentral\SiteBundle\Entity\Institution
            inversedBy: credentials
            joinTable:
              name: credentials_institutions
              joinColumns:
                credential_id:
                  referencedColumnName: id
              inverseJoinColumns:
                institution_id:
                  referencedColumnName: id
            nullable: true
        courses:
            targetEntity: ClassCentral\SiteBundle\Entity\Course
            inversedBy: credentials
            joinTable:
              name: credentials_courses
              joinColumns:
                credential_id:
                  referencedColumnName: id
              inverseJoinColumns:
                course_id:
                  referencedColumnName: id
            nullable: true
    lifecycleCallbacks: {  }
