class_central_credential:
    resource: "@ClassCentralCredentialBundle/Resources/config/routing.yml"
    prefix:   /

ClassCentralSiteBundle:
    resource: "@ClassCentralSiteBundle/Resources/config/routing.yml"
    prefix: /

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: ClassCentralSiteBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]