credential_review:
  pattern: /certificate/{credentialId}/review/new/
  defaults: { _controller: ClassCentralCredentialBundle:CredentialReview:new }

credential_review_save:
  pattern: /certificate/review/save/{credentialId}
  defaults: { _controller: ClassCentralCredentialBundle:CredentialReview:save}

credentials_reviews:
  pattern: /certificate/reviews
  defaults: { _controller: ClassCentralCredentialBundle:CredentialReview:credentialsReviews }

credential_page:
  pattern: /certificate/{slug}/{tab}
  defaults: { _controller: ClassCentralCredentialBundle:Credential:credential, tab: 'overview' }

credentials:
  pattern: /certificate
  defaults: { _controller: ClassCentralCredentialBundle:Credential:credentials }