credential_review:
  pattern: /certificate/{credentialId}/review/new/
  defaults: { _controller: ClassCentralCredentialBundle:CredentialReview:new }

credential_review_save:
  pattern: /certificate/review/save/{credentialId}
  defaults: { _controller: ClassCentralCredentialBundle:CredentialReview:save}

credentials_reviews:
  pattern: /certificate/reviews
  defaults: { _controller: ClassCentralCredentialBundle:CredentialReview:credentialsReviews }