credential_review:
  pattern: /credential_review
  defaults: { _controller: ClassCentralCredentialBundle:CredentialReview:new }

credential_review_save:
  pattern: /certificate/review/save/{credentialId}
  defaults: { _controller: ClassCentralCredentialBundle:CredentialReview:save}