credential:
    pattern:  /
    defaults: { _controller: "ClassCentralCredentialBundle:Credential:index" }

credential_show:
    pattern:  /{id}/show
    defaults: { _controller: "ClassCentralCredentialBundle:Credential:show" }

credential_new:
    pattern:  /new
    defaults: { _controller: "ClassCentralCredentialBundle:Credential:new" }

credential_create:
    pattern:  /create
    defaults: { _controller: "ClassCentralCredentialBundle:Credential:create" }
    requirements: { _method: post }

credential_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ClassCentralCredentialBundle:Credential:edit" }

credential_update:
    pattern:  /{id}/update
    defaults: { _controller: "ClassCentralCredentialBundle:Credential:update" }
    requirements: { _method: post|put }

credential_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ClassCentralCredentialBundle:Credential:delete" }
    requirements: { _method: post|delete }
