ClassCentral\SiteBundle\Entity\Follow:
    type: entity
    table: follow
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        item:
            type: string
            length: 15
            fixed: true
            nullable: false
        itemId:
            type: integer
            unsigned: false
            nullable: false
            column: item_id
        created:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
